### ISSUE TITLE
Ability to replace from file/template

### ISSUE THREAD

**Issue by stp-ip** [echocat/caddy-filter#1]
Awesome to see something like caddy-filter coming together. One suggestion would be the ability to include html from a file or template. This would simplify the configuration especially for bigger injects. Such as adding a global navigation or notices etc.

**Comment by blaubaer** [comment]
Hi @stp-ip!

You are right. I already think about that. I will also add this feature in the future.

But there is one thing to keep in mind: Injecting content from external files could impact the performance in a very bad way - if the files are too huge.

Thank you for feedback.

**Comment by stp-ip** [comment]
Yeah it probably makes sense to chain it with a cache middleware (when available).

**Comment by blaubaer** [comment]
I added this ability. I will close this issue here until I can verify that the changes here will also served by the caddy download page.
