### ISSUE TITLE
basicauth plugin

### ISSUE THREAD

**Issue by GuillaumeCisco** [echocat/caddy-filter#10]
I'm encountering a weird behavior using filter with basicauth.
If I specify a basicauth with:
```
basicauth / user password
```
The basic auth works welll, A prompt is asked and after filling the credentials I can access my website.
If I add a filter rule and reload my config, example:
```
filter rule {
        content_type application/x-javascript
        search_pattern USER
        replacement admin
    }
```
It works too, my browser doesn't prompt me for credentials and I can access my website with the replacement effective.

But, If I use both with a clean cache browser, it does not work anymore.
The browser display a text with `401 Unauthorized` and a `200` status code.
No prompt is displayed for filling credentials.

Does filter works well with basicauth or am I missing something?

**Comment by ghost** [comment]
This problem happened to me today. If I set `Caddyfile` with
```
mydomain {
  gzip
  timeouts none
  basicauth / 123 456
  filter rule {
    content_type text/.*
    search_pattern aaaaa
    replacement bbbbb
  }
}
```
And I visit `mydomain`, the browser will return `401 Unauthorized` and a `401` status code. If I set `Caddyfile` with
```
mydomain {
  gzip
  timeouts none
  basicauth / 123 456
}
```
The Browser will ask me username and password. I have searched with Google, but I can't find a solution. Do you have a solution?
