### ISSUE TITLE
Headers will not be set if rules only applies partially

### ISSUE THREAD

**Issue by stp-ip** [echocat/caddy-filter#12]
Seems like filter is preventing the redirect and rewriting it to a page like:

```
<a href="https://www.example.com">Found</a>.
```

https://www.example.com is the page to redirect to using:

Works:
```
:8080 {
  redir / https://www.example.com 302
}
```

Interferes:
```
:8080 {
  redir / https://www.example.com 302
  filter rule {
    content_type "text/html.*"
    search_pattern "<body>"
    replacement "<body><div style=\"background-color: #000; padding: 10px; margin-bottom: 5px; color: #fff; text-align: center;\"><h1>Some new heading.</h1></div>"
  }
}
```

**Comment by blaubaer** [comment]
[Test_redir](../blob/master/integration_test.go#L83) with [integrationTest.Test_redir.conf](../blob/master/resources/test/integrationTest.Test_redir.conf) describes the problem and they are now fixed. Thank for your input.
