### ISSUE TITLE
Provide Example with mitm detection

### ISSUE THREAD

**Issue by TheOneValen** [echocat/caddy-filter#13]
Hi!

I think this plugin would be great to inject a warning (box) into any webpage if the mitm detection of caddy detected an attack.

Is this already possible? How would I need to configure it. I think this would look great in the docs ;-)

Greetings!

**Comment by blaubaer** [comment]
Hi!

This is currently not possible and might be a new feature request. It is more a less another condition to be matched to let the filtering happen - like `content_type` or `path` directive. I have to think about it how to implement it.

But for now I close this ticket and will open it if I decide to add more conditions.

Cheers
