### ISSUE TITLE
it seems can not replace non-english character

### ISSUE THREAD

**Issue by listeng** [echocat/caddy-filter#22]
I try to write the config like that:

filter rule {
	content_type text/html
	search_pattern 电影
	replacement 电视
}

and save it to UTF-8 encoding file. But the results are still original words. Thanks for your work.

**Comment by blaubaer** [comment]
Dear @listeng,

I have tested successfully that this works. It might be that your `content_type` filter is not optimal. Please try to use `content_type "text/html.*"` instead to also cover if there is the encoding included in the content type.

Cheers
