### ISSUE TITLE
multiline match / whole body replacement

### ISSUE THREAD

**Issue by rmoriz** [echocat/caddy-filter#23]
One thing I'm still missing with caddy is the following functionality available in nginx:

```
  location /robots.txt {
    return 200 "User-agent: *\nDisallow: /";
  }
```

This will return a custom `/robots.txt` to disable bots from crawling the site for specific instances of the deployed websites (e.g. public staging environments). 

caddy-filter allows something like:

```
  filter rule {
    path /robots.txt
    search_pattern .*
    replacement "User-agent: *\nDisallow: /"
  }
```
however this returns the replacement for each existing line in the "real" `robots.txt`.

As regex are the wrong thing for this job anyway, I would love to have an option without a `search_pattern` that just returns the replacement. This should also be returned if there was no matching response yet.

**Comment by torch2424** [comment]
Actually I just figured it out. You can enable the multiline/singleline match using (?flags) in the actual regex.

http://grokbase.com/t/gg/golang-nuts/1523qx73zm/go-nuts-how-to-enable-multi-line-mode-in-go-package-regexp
https://stackoverflow.com/questions/37106834/golang-multiline-regex-not-working

Therefore giving us:

```
    filter rule {
        content_type text/html.*
        search_pattern (?ms)^.*
        replacement @YOUR/REPLACEMENT/FILE
    }
```

I am sure you know, but just for other people who stumble upon this, the key is: `search_pattern (?ms)^.*`. The regex `(?ms)^.*` will match the entire file including the newlines to return a single match :)

**Comment by blaubaer** [comment]
Hi,

that is true as you described above. But keep in mind to do not create the pattern to broad because it could hardly harm the performance, if always that many bytes are required to be evaluated (the problem always with RegExp 😄).

I close this issue now.

Cheers
