### ISSUE TITLE
when enable http.filter in Caddyfile, Failed to start

### ISSUE THREAD

**Issue by yukeiyang** [echocat/caddy-filter#31]
**I installed http.filter in my caddy host. But when i enable it in caddyfile, Can not start candy service.**
**This is my Caddyfile:**

https://example.com {
gzip
tls /etc/caddy/ssl/letsencrypt.pem /etc/caddy/ssl/example.com-key.pem
proxy / https://another-example.com
filter rule {
content_type text/.*
search_pattern apis.google.com
replacement apix.example.com
}
}

https://apix.example.com {
gzip
tls /etc/caddy/ssl/letsencrypt.pem /etc/caddy/ssl/example.com-key.pem
proxy / apis.google.com
}

**Please help.**

**Comment by yukeiyang** [comment]
When remove the http.filter code-block in Caddyfile, Caddy can be started. So, how can i add filter in this correctly?

This only for China GFW. 
Fuck GFW!

**Comment by blaubaer** [comment]
Could you maybe provide some information what the caddy is saying and how you downloaded caddy?

**Comment by yukeiyang** [comment]
@blaubaer thanks for your reply.

**I installed the official latest version, and succeed to configure the http.filter.**
I think this issue caused by the 3rd script caddy version. 
anyway, thanks.
