### ISSUE TITLE
Error Downloading From Caddy Website

### ISSUE THREAD

**Issue by putradimas** [echocat/caddy-filter#40]
caddy v1.0.0
http.filter v0.12

When I tried to download caddy from https://caddyserver.com/download with http.filter plugin enabled, the build site gives error without any code. I tried to download the Windows and Linux binary, both get the same error.

![Download Caddy](https://user-images.githubusercontent.com/7010096/57057836-fd004d00-6cd5-11e9-9a64-aca85b76214e.png)

I really need the filter plugin. Please take a look at this problem.

Thanks!

**Comment by wzc0x0** [comment]
caddy v1.0.0
http.filter v0.12

Something error just now!

`curl https://getcaddy.com | bash -s personal hook.service,http.filter
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0  18103      0 --:--:-- --:--:-- --:--:-- 18177
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 Internal Server Error
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"`

**Comment by pwhodges** [comment]
I am seeing the same error, and I cannot use Caddy without this plugin!

Looking forward to seeing this resolved...

**Comment by mholt** [comment]
I think this is because the tag does not use semantic versioning. More info here: https://caddy.community/t/caddy-v1-0-0-build-fails-when-http-filter-plugin-included/5754/7?u=matt

**Comment by blaubaer** [comment]
So, lets try if _just_ using a different version scheme will solve the issue. I will prepare a new release. :-)

**Comment by blaubaer** [comment]
Download possible again. :-)

**Comment by pwhodges** [comment]
Thanks!

**Comment by mholt** [comment]
Thank you for testing that @blaubaer ! I will update the Caddy website's instructions and recommend other plugin authors do the same as far as releases go.

**Comment by jscottelblein** [comment]
> Thank you for testing that @blaubaer ! I will update the Caddy website's instructions and recommend other plugin authors do the same as far as releases go.

Maybe even directly notify the ones that aren't currently following version semantics; I just noticed that there are still several. :)

**Comment by mholt** [comment]
Want to do that, but been so busy!
