### ISSUE TITLE
Caddy API method caddy.Controller.IncrNest not longer supported

### ISSUE THREAD

**Issue by vteslia** [echocat/caddy-filter#7]
Hi, 

I wan't to test caddy-filter plugin but I am unable to do "go get github.com/echocat/caddy-filter" with the following error:

```
root@caddy:~# go get github.com/echocat/caddy-filter
# github.com/echocat/caddy-filter
.gvm/pkgsets/go1.8/global/src/github.com/echocat/caddy-filter/init.go:66: controller.IncrNest undefined (type *caddy.Controller has no field or method IncrNest)
root@caddy:~#
```

It seems error is related to changing caddy plugins API.
Similar issue with another plugin https://github.com/nicolasazrak/caddy-cache/issues/8

Could you check?

**Comment by blaubaer** [comment]
@vteslia: Thank you for your contribution. I will check this.

**Comment by blaubaer** [comment]
Verified.

This is based on the intention to provide a fault tolerant configuration. A function was removed from caddy API which does not longer support this feature. I will remove it.
