### ISSUE TITLE
Content-Length: 0 on subsequent requests

### ISSUE THREAD

**Issue by smancke** [echocat/caddy-filter#8]
I started using the filter plugin, but got the problem, that subsequent requests are not always working.

What I have done:
- Build caddy and the filterplugin from source (current master)
- Simple filter configuration
- Visit the page with chrome -> page served
- Reload (F5) -> blank page/content-type: 0
- Full-Reload (Strg+Shift+R) -> page served

When I remove the filter plugin, everything works fine.
It seems to have something to do with the connection or keep alives, but I could not reproduce it with firefox or go http client, so I don't know what chrome is doing different on subsequent calls.

My filter configuration:
```
  filter rule {
    content_type   (text/html.*|application/javascript.*)
    search_pattern @@mailck_api_domain@@
    replacement    api.{$mailck_web_domain}
  }
```

**Comment by stp-ip** [comment]
Same issue. Couldn't really figure out what the trigger is for caddy+filter to send the 0 content-length responses.

```
    filter rule {
      content_type "text/html.*"
      search_pattern "<body>"
      replacement "<body><div>test</div>"
    }
```

**Comment by danhawkes** [comment]
This is the same as issue #11: the upstream server is likely returning `302 unmodified`, but the filter is changing that to `200`, so the page renders the zero-length response. You can test by sending/not sending a cache header with the request.

**Comment by stp-ip** [comment]
@danhawkes for me there is no upstream server. Caddy is serving plain static files and the filer is just a middleware enabled on the same caddy instance.

**Comment by stp-ip** [comment]
Thanks works fine.
